services:
  lancommander:
    image: lancommander/lancommander:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    x-runtipi:
      is_main: true
      internal_port: 1337
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    ports:
      - 1337:1337/tcp
      - 35891:35891/udp
      - 213:213/udp

x-runtipi:
  schema_version: 2