services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - TZ=Asia/Tokyo
      - SECRET=longstring
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_NAME=yamtrack
      - DB_USER=yamtrack
      - DB_PASSWORD=${AP_POSTGRES_PASSWORD}
      - DB_PORT=5432
    ports:
      - "8000:8000/tcp"
    x-runtipi:
      is_main: true
      internal_port: 8000

  db:
    image: postgres:16-alpine
    container_name: yamtrack-db
    environment:
      - POSTGRES_DB=yamtrack
      - POSTGRES_USER=yamtrack
      - POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: yamtrack-redis
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
x-runtipi:
  schema_version: 2