services:
  yamtrack:
    image: ghcr.io/dannyvfilms/yamtrack:latest
    environment:
      - TZ=${TIMEZONE}
      - SECRET=${SECRET}
      - REDIS_URL=redis://redis:6379
      - DB_HOST=db
      - DB_NAME=yamtrack
      - DB_USER=yamtrack
      - DB_PASSWORD=${SECRET}
      - DB_PORT=5432
      - TMDB_LANG=${TMDB_LANG}
      - ADMIN_ENABLED=TRUE
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ${APP_DATA_DIR}/data/templates:/yamtrack/templates
    x-runtipi:
      is_main: true
      internal_port: 8000

  redis:
    image: redis:8-alpine
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16-alpine
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=yamtrack
      - POSTGRES_USER=yamtrack
      - POSTGRES_PASSWORD=${SECRET}
      - POSTGRES_HOST_AUTH_METHOD=trust
    x-runtipi:
      add_to_main_network: true
x-runtipi:
  schema_version: 2
